roots = [
   "^Main.main$"
 , "^Spec.main$"
 , "^Paths_.*"
]

root-instances = [
   { class = '\.Eq$' }
 , { class = '\.Show$' }
 , { class = '\.Read$' }
 , { class = '\.Enum$' }
 , { class = '\.Bounded$' }
 , { class = '\.Generic$' }
 , { class = '\.Ord$' }
 , { class = '\.Num$' }
 , { class = '\.Real$' }
 , { class = '\.Integral$' }
 ]
